version: '3.9'

services:
  nest-backend:
    container_name: nest-app
    image: nest-api
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - 5000:5000
    environment:
      - DB_TYPE=postgres
      - DB_SCHEMA=public
      - PG_HOST=roundhouse.proxy.rlwy.net
      - PG_USER=postgres
      - PG_PASSWORD=*BDD**FBd-EaeAdFFCBd*2FAeE3e-Ga*
      - PG_DB=railway
      - PG_PORT=52584
    networks:
      - backend_network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
      - redis

networks:
  backend_network:
    driver: bridge

volumes:
  nest-backend: